apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels: #rs or deployment
      app: ng-deploy-80
  template:
    metadata:
      labels:
        app: ng-deploy-80
    spec:
      containers:
      - name: ng-deploy-80
        image: nginx
        #image: mysql:5.6.46
        #env:
          # Use secret in real usage
          #- name: MYSQL_ROOT_PASSWORD
          #value: magedu123456
        ports:
        - containerPort: 80
        volumeMounts:
        - name: rbd-data1
          #mountPath: /var/lib/mysql
          mountPath: /usr/share/html/ceph
      volumes:
        - name: rbd-data1
          rbd:
            monitors:
            - '192.168.40.151:6789'
            - '192.168.40.152:6789'
            - '192.168.40.153:6789'
            pool: dzzz-rbd-pool
            image: dzzz-image-img1
            fsType: ext4
            readOnly: false
            user: dzzz-xks
            keyring: /etc/ceph/ceph.client.dzzz-xks.keyring
