apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
    - name: rbd-data1
      mountPath: /data
  volumes:
    - name: rbd-data1
      rbd:
        monitors:
        - '192.168.40.151:6789'
        - '192.168.40.152:6789'
        - '192.168.40.153:6789'
        pool: dzzz-rbd-pool
        image: dzzz-image-img1
        fsType: ext4
        readOnly: false
        user: dzzz-xks
        keyring: /etc/ceph/ceph.client.dzzz-xks.keyring
