apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels: #rs or deployment
      app: ng-deploy-80
  template:
    metadata:
      labels:
        app: ng-deploy-80
    spec:
      containers:
      - name: ng-deploy-80
        image: nginx
        ports:
        - containerPort: 80

        volumeMounts:
        - name: rbd-data1
          mountPath: /usr/share/nginx/html/rbd
      volumes:
        - name: rbd-data1
          rbd:
            monitors:
            - '192.168.40.151:6789'
            - '192.168.40.152:6789'
            - '192.168.40.153:6789'
            pool: dzzz-rbd-pool
            image: dzzz-image-img1
            fsType: ext4
            readOnly: false
            user: dzzz-xks
            secretRef:
              name: ceph-secret-dzzz-xks
