apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-storage-class-dzzz-xks
  annotations:
    storageclass.kubernetes.io/is-default-class: "false" #设置为默认存储类
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.40.151:6789,192.168.40.152:6789,192.168.40.153:6789
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: default
  pool: dzzz-rbd-pool
  userId: dzzz-xks
  userSecretName: ceph-secret-dzzz-xks
